function main() 
{
  GENERATE_STATIC_TASKS();

  GET_TASKS();
  GENERATE_TASKS();
  
  ADD_ROWS(TASK_SHEET);
  WIPE_SHEET(TASK_SHEET);
  PRINT_TASKS();
  SORT_SHEET(TASK_SHEET, 5);

  UPDATE_CHECKBOXES(CALENDAR_SHEET, TASK_LIST);
}